# Generated by Django 4.2.5 on 2023-09-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task.task'),
        ),
    ]
